config/routes.rb
LssspP2::Application.routes.draw do
  resources :credits

  resources :examinations do
    get 'active', :on=>:member
    get 'export', :on=>:collection

  end

  resources :coupons
  resources :verifications

  get "user_info/index"
  devise_for :users, :path_names => {:sign_up => "register"}
=begin
devise_for :users, :as => "", :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }
match "login" => "devise/sessions#new", :as => :new_user_session
match "logout" => "devise/sessions#destroy", :as => :destroy_user_session
match "register" => "devise/registrations#new", :as => :new_user_registration
=end
  resources :followings

  #Superadmin Namespace
  #--------------------------------------------------------------------------
  namespace :super_admin do
    resources :users do
      get 'approve', :on=>:member
      get 'profile', :on=>:member
      get 'upload', :on=>:collection
      get 'export', :on=>:collection
      get 'reset', :on=>:member
      post 'csv_import',:on=>:collection
    end
    #---------------------------------------------------------------------------
    # ROles
    #---------------------------------------------------------------------------
    resources :roles do
      member do
        get 'permissions'
        put 'assign_permissions'
        get 'active'
      end
      get 'export', :on=>:collection
    end
  end
  #--------------------------------------------------------------------------
  #Student namespace
  #--------------------------------------------------------------------------
  namespace :student do
    resources :service_providers do
      get 'my_service_providers', :on=>:collection
      post 'coupon_check',:on=>:collection
    end
    resources :certifications, :only => [:index] do
      get 'assignments', :on=>:member
      get 'download', :on=>:member
      get 'assign',:on=>:member
      get 'subscribe', :on=>:member
    end
    #resource :exam
  end
  ######## Exam
  match "exam/:id/:status" => "student/exam#index", :as=>:exam
  match "active_question" => "student/exam#active_question", :as=>:active_question
  match "update_answer" => "student/exam#update_answer"
  match "finish_exam/:id" => "student/exam#finish_exam", :as=>:finish_exam

  match "save_exam/:id" => "student/exam#save_exam", :as=>:save_exam

  match "review_question" => "student/exam#review_question"

  ###### Subscribe/Unsubscribe exam for user from super_admin
  match "/:name/:id/subscribe_to/:provider_id"=>"student/certifications#subscribe",:as=>:subscribe_certification
  match "/:id/un_subscribe"=>"student/certifications#un_subscribe",:as=>:un_subscribe_certification

  #--------------------------------------------------------------------------
  #Service Provider Namespace
  #--------------------------------------------------------------------------
  namespace :service_provider do
    resources :certifications do
      get 'my_certifications', :on=>:collection
      get 'export', :on=>:collection
    end
    resources :assessors, :students do
      get 'approve', :on=>:member
      get 'export', :on=>:collection
      get 'students', :on=>:member
    end
  end
  #--------------------------------------------------------------------------
  namespace :assessor do
    resources :assignments
    resources :students, :only => [:index] do
      get 'manage_assignments', :on=>:collection
      post 'manage_assignments', :on=>:collection
      get 'pending_assignments', :on=>:collection
      post 'pending_assignments', :on=>:collection
      post 'assign_assignments', :on=>:collection
      get 'assignments', :on=>:member
      get 'download', :on=>:member
      #  post 'update_assignment_result' ,:on=>:member
    end
  end
  #namespace(:assessor){ resources :assignments }
  #----------------------------------------------------------------------------
  namespace :catalog do
    resources :topics, :subtopics do
      get 'active', :on=>:member
      get 'export', :on=>:collection

    end
    resources :certifications do
      get 'active', :on=>:member
      get 'export', :on=>:collection
      get 'load_subtopics', :on=>:collection
    end
    resources :questions do
      get 'active',:on=>:member
      get 'export',:on=>:collection
     end
  end

  resources :payment_gateways do
    get 'active', :on=>:member
  end

  #match "certifications/purchased" => "certification/exams#purchased",:as=>:certifications_purchased
  match "certifications/purchased" => "certifications#index", :as=>:certifications_purchased
  match "certification/purchased" => "certifications#purchased_certification" #,:as=>:purchased_certification
  match "certifications/exams" =>"certifications#exams"
  match "manage_certifications" =>"certifications#manage_certifications"
  match "user_info/:id" => "user_info#index", :as=>:user_info
  match "certifications/purchased/:id/edit_score" => "certifications#edit_score", :as=>:edit_score
  match "certifications/purchased/:id/update_score" => "certifications#update_score", :as=>:update_score

  root :to => "home#index"

# Note: This route will make all actions in every controller accessible via GET requests.
  match ':controller(/:action(/:id(.:format)))'
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
  has_many :authorizations,:dependent=>:destroy
  has_many :permissions, :through => :authorizations
  
  accepts_nested_attributes_for :authorizations, :allow_destroy => true 
  
# START --> Validations 
#------------------------------------------------------------------------------------------------------
  validates :name,:presence=>true, :uniqueness => true, :length => { :maximum => 25}
  validates_length_of :description, :maximum => 1000, :allow_blank => true
#------------------------------------------------------------------------------------------------------

# Class Methods
#Scopes are dead in Rails3(from ref: http://www.railway.at/2010/03/09/named-scopes-are-dead/)
#So use class methods instead
#------------------------------------------------------------------------------------------------------      
  class << self
    def search(query)
      if query
        where(:name.matches => "%#{query}%") #from meta_where gem
      else
       scoped
      end
    end
    def recent
      includes([:users]).order('roles.created_at DESC').limit(4)
    end
  end
#------------------------------------------------------------------------------------------------------  
end

app/controllers/super_admin/exams_controller.rb
class SuperAdmin::ExamsController < ApplicationController
  def index
    @student_exams = StudentExam.finished.paginate(:page =>params[:page],:per_page=>10 )
  end
end

app/controllers/super_admin/roles_controller.rb
class SuperAdmin::RolesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :recent,:only=>[:index]
  load_and_authorize_resource
  layout "application", :except => [:show, :edit]

  def index
    @roles = Role.search(params[:search])
    @role = Role.new
  end

  def show
    @role = Role.find(params[:id])
  end

  def new
    @role = Role.new
  end

  def create
    @role = Role.new(params[:role])
    if @role.save
      #redirect_to [:super_admin, @role], :notice => "Successfully created Role."
      redirect_to super_admin_roles_path, :notice => "Successfully created Role."
    else
      render :action => 'new'
    end
  end

  def edit
    @role = Role.find(params[:id])
  end

  def update
    @role = Role.find(params[:id])
    if @role.update_attributes(params[:role])
      redirect_to super_admin_roles_path, :notice  => "Role updated Successfully."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @role = Role.find(params[:id])
    #@role.destroy
    redirect_to super_admin_roles_url, :notice => "Successfully destroyed Role."
  end

  def permissions
    @role = Role.find(params[:id])
=begin
    if @role.authorizations.blank? # already permissions exists don't build childrens
      #define Models and their actions in Hash of Arrays
     
      @abilities.each do |key,values|
        @role.authorizations_attributes = [{:name=>key}] #construct form attributes for authorizations(using nested attributes)
      end
      #construct form attributes for permissions on above created authorizations
      @role.authorizations.each do |authorization|
      #to build autharization.permissions_attributes = [{:name=>'create'},{:name=>'update'}],
      #get the array of values from abilities Hash with key already assigned to authorization
        authorization.permissions_attributes =  @abilities[authorization.name].collect!{|val| {:name=>val} }
      end
    end
=end  
  end

  def assign_permissions
    @role = Role.find(params[:id])
    ## delete all authorizations and create again same for permissions
    @role.authorizations.clear
    if @role.update_attributes(params[:role])
      flash[:notice] = "Group Permissions Assigned Successfully.."
      redirect_to super_admin_roles_path
    else
      #flash.now[:error] = "ERROR"
      render 'permissions'
    end
  end

  def active
    super(Role)
  end

   def export
    require 'fastecsv'
    roles = Role.search(params[:search]).order("name")
    outfile = "Roles -" + Time.now.strftime("%d-%m-%Y-%H-%M-%S") + ".csv"
    csv_data = FasterCSV.generate do |csv|
      csv << ["Name","Description","Active?","Created At"]
      roles.each do |role|
        csv << [role.name,role.description,role.active? ? 'Yes' : 'No',role.created_at.strftime('%m.%b.%y')]
      end
    end
    send_data csv_data,
    :type => 'text/csv; charset=iso-8859-1; header=present',
    :disposition => "attachment; filename=#{outfile}"
  end
  private

  def recent
    @recent = Role.recent
  end
end

app/controllers/super_admin/users_controller.rb
require 'csv'
class SuperAdmin::UsersController < ApplicationController
  before_filter :authenticate_user! #, #:recent#, :except => [:show, :index]
                                    #before_filter :accessible_roles, :only => [:new, :edit, :show, :update, :create]
                                    #load_and_authorize_resource #:only => [:show,:new,:destroy,:edit,:update]
                                    #    layout "application", :except => [:show, :edit]
  layout "application", :except => [:show, :edit]

  def index
    #@users = 
    @users = User.search(params[:search], current_user, params[:id]).paginate(:page =>params[:page], :per_page=>20).order("created_at DESC")
    @user = User.new(:role_id=>params[:id])
  end

  def new
    respond_to do |format|
      format.json { render :json => @user }
      format.xml { render :xml => @user }
      format.html
    end
  end

  def show
    @user = User.find(params[:id])
=begin
    respond_to do |format|
      format.json { render :json => @user }
      format.xml  { render :xml => @user }
      format.html
    end

  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:json, :xml, :html)
=end
  end

  def edit
    @user = User.find(params[:id])
=begin
    respond_to do |format|
      format.json { render :json => @user }
      format.xml  { render :xml => @user }
      format.html
    end

  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:json, :xml, :html)
=end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to super_admin_users_path, :notice => "User deleted Successfully."
=begin
    @user.destroy!

    respond_to do |format|
      format.json { respond_to_destroy(:ajax) }
      format.xml  { head :ok }
      format.html { respond_to_destroy(:html) }
    end

  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:json, :xml, :html)
=end
  end

  def create
    @user = User.new(params[:user])
    if (params[:user][:role_id].to_i == 4)
      @user.enrollment_no = params[:user][:password]
    else
      @user.enrollment_no= '---'
    end

    if @user.save
      flash[:notice] = "User Created Successfully."
      respond_to do |format|
        format.json { render :json => @user.to_json, :status => 200 }
        format.xml { head :ok }
        if has_role?(:service_provider)
          @follow = Following.new(:user_id=>@user.id, :follower_id=>params[:user][:provider_id])
          @follow.save
          format.html { redirect_to :controller => service_provider_students_path }
        else
          format.html { redirect_to :action => :index }

        end
      end
    else
      respond_to do |format|
        format.json { render :text => "Could not create user", :status => :unprocessable_entity } # placeholder
        format.xml { head :ok }
        format.html { render :action => :new, :status => :unprocessable_entity }
      end
    end
  end


  def approve
    @user = User.find(params[:id])
    @user.update_attribute('approved', @user.approved? ? false : true)
    respond_to do |format|
      format.js
    end
  end

  def update
    if params[:user][:password].blank?
      [:password, :password_confirmation, :current_password].collect { |p| params[:user].delete(p) }
    else
      @user.errors[:base] << "The password you entered is incorrect" unless @user.valid_password?(params[:user][:current_password])
    end

    respond_to do |format|
      if @user.errors[:base].empty? and @user.update_attributes(params[:user])
        flash[:notice] = "User Details updated Successfully"
        format.json { render :json => @user.to_json, :status => 200 }
        format.xml { head :ok }
        format.html { render :action => :edit }
      else
        format.json { render :text => "Could not update user", :status => :unprocessable_entity } #placeholder
        format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
        format.html { render :action => :edit, :status => :unprocessable_entity }
      end
    end

  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:js, :xml, :html)
  end

  def profile
    @user = User.find(params[:id])
  end

  def csv_import
    csv_file = params[:file]
    n=0
    if has_role?(:super_admin)
      CSV.new(csv_file.tempfile, :col_sep => ",").each do |row|
        @user = User.create do |u|
          u.name =row[0]
          u.last_name = row[1]
          u.email = row[2]
          u.secondary_number = row[4]
          u.primary_number = row[3]
          u.approved = '1'
          role = Role.find_by_name(row[5].strip)
          ran_num = rand(10_000_000_000-1_000_000_000)+1_000_000_000
          u.password = u.password_confirmation = ran_num
          if role.name == "Student"
            u.enrollment_no = ran_num
          else
            u.enrollment_no= '---'
          end
          u.role_id=role.id
        end
        @user.save
        n=n+1
      end
    elsif has_role?(:service_provider)
      CSV.new(csv_file.tempfile, :col_sep => ",").each do |row|
        @user = User.create do |u|
          u.name =row[0]
          u.last_name = row[1]
          u.email = row[2]
          u.secondary_number = row[4]
          u.primary_number = row[3]
          u.approved = '1'
          ran_num = rand(10_000_000_000-1_000_000_000)+1_000_000_000
          u.password = u.password_confirmation = ran_num
          u.enrollment_no = ran_num
          u.role_id=params[:role_id]
        end
        @user.save
        @follow = Following.new(:user_id=>@user.id, :follower_id=>params[:provider_id])
        @follow.save

        n=n+1
      end
    end

    flash[:notice]= "#{n} Users are imported Successfully"
    respond_to do |format|
      if has_role?(:service_provider) and params[:role_id] == 4
        format.html { redirect_to :controller => service_provider_students_path }
      elsif
      format.html { redirect_to :controller => service_provider_assessors_path }
                                                                                    else
        format.html { redirect_to :action => :index }
        format.xml { head :ok }
      end
    end
  end

  def upload
  end

  def export
    require 'fastercsv'
    users = User.order("created_at")
    outfile = "Users -" + Time.now.strftime("%d-%m-%Y-%H-%M-%S") + ".csv"
    csv_data = FasterCSV.generate do |csv|
      csv << ["First Name", "Last Name", "Enrollment #", "Email", "Primary Contact", "Status", "Created At"]
      users.each do |u|
        csv << [u.name, u.last_name, u.enrollment_no, u.email, u.primary_number, u.approved? ? 'Yes' : 'No', u.created_at.strftime('%m.%b.%y')]
      end
    end
    send_data csv_data,
              :type => 'text/csv; charset=iso-8859-1; header=present',
              :disposition => "attachment; filename=#{outfile}"
  end

  def reset
    @user = User.find(params[:id])
    @user.password= @user.password_confirmation=@user.enrollment_no
    respond_to do |format|
      if @user.update_attributes(params[:user])
        ExamNotifier.reset_password(@user)
        format.html { redirect_to(super_admin_users_path, :notice => 'User Password is  successfully Reset.') }
        format.xml { head :ok }
      else
      end
    end
  end

end

app/helpers/super_admin/exams_helper.rb
module SuperAdmin::ExamsHelper
end

app/helpers/super_admin/roles_helper.rb
module SuperAdmin::RolesHelper
end

app/views/super_admin/roles/_form.html.erb
<%= simple_form_for [:super_admin, @role],:validate=>true do |f| %>
  <%= f.error_messages %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.submit 'Submit',:disable_with=>'Please wait...' %>
<% end %>

app/views/super_admin/roles/_recent.html.erb
<div class="recent_items">
	<div class="margin">
		<h3>Recent Groups</h3>
        <% if @recent.blank? %>
          No Groups Added Yet...
        <% else %>
         <% for role in @recent %>
		<div id="margin">
			<div class="left">&nbsp;</div>
			<div class="right">&nbsp;</div>
			<div class="left-to-right">
				<div class="pen">&nbsp;</div>
				<div class="text">
                     <%=link_to role.name ,super_admin_role_path(role),:class=>'usuallink',:rel=>"facebox"%>
					<div style="margin: 8px 0px;">&nbsp;</div>
				</div>
				<div class="date">
                    (<b><%=role.users.size %></b>)
                </div>
			</div>
		</div>
         <% end %>
       <% end %>
		<div class="see_all">
			<a href="/super_admin/roles">
			 View all Groups
			<img hspace="2" border="0" alt="" src="/images/blue^.gif">
			</a>
		</div>
	</div>
</div>

app/views/super_admin/roles/_role.html.erb
<%= content_tag_for(:tr,role,:class=>cycle('even', 'odd')) do -%>
    <td><%= highlight(role.name,params[:search]) %></td>
    <td><%= role.description %></td>
    <td><%= link_to_active(role,active_super_admin_role_path(role)) %></td>
    <td><%= link_to role.users.size,super_admin_users_path(:id=>role.id),:class=>'tipTipRight',:title=>users_list(role.users) %></td>
    <td>
      <%=link_to 'Edit Permissons',permissions_super_admin_role_path(role),:class=>'usuallink bold_text'%> |
      <%= link_for_show_pop([:super_admin, role]) %>
      <%= link_for_edit_pop( edit_super_admin_role_path(role)) %>
      <%= link_for_destroy([:super_admin, role]) %>
    </td>
<% end %>
		

app/views/super_admin/roles/active.js.erb
$("#active_<%=@model.id%>").html("<%=escape_javascript(link_to @model.active? ? image_tag('tick.gif') : image_tag('cros.gif'),
                                     active_super_admin_role_path,:remote=>true)%>")

app/views/super_admin/roles/edit.html.erb
<% title "LSSSP | Edit Group" %>
<% content_for :sub_heading do %>
  <%= sub_heading('Groups',"Edit #{@role.name}") %>
<% end %>
<%= render 'form' %>

<!--
<div class="link_buttons">
  <%= link_to_show([:super_admin, @role]) %> 
  <%=link_to_all(super_admin_roles_path)%>
</div>
-->

app/views/super_admin/roles/index.html.erb
<% title "LSSSP : Manage Groups" %>
<% content_for :sub_heading do %>
  <%= sub_heading('LSSSP','Manage Groups') %>
<% end %>
<% content_for :left_panel do  %>
<td valign="top" width="250">
  <%= render 'common/search' %>
  <%=render 'recent' %> 
</td>
<% end %>
<div class="help_text">
 Area for managing groups used to assign certain permissions to LSSSP service sections for different groups members. <br/>
 Along with creating, managing and removing groups for your LSSSP service users,.
</div>
<div id="container">
<%= link_to "Add New Group", "#",:class=>'usuallink bold_text',:id=>'add_new' %>
  | <%=link_to 'Export',export_super_admin_roles_path,:class=>'usuallink bold_text' %>
</div>
<div id="new_form">
<%=render 'form' %>
</div>
<% if @roles.blank? %>
  <div class="error_msg">Sorry No Groups Found..!</div>
<% else %>
<table class="tablesorter">
	<thead>
		<tr>
			<th>Name</th>
			<th>Description</th>
            <th>Status</th>
            <th>Users</th>
			<th>Actions</th>
		</tr>
	</thead>
	
	<tbody>
		<%=render @roles %>
	</tbody>
</table>
<% end %>
<!--<p>
	<%= link_to "New Group", new_super_admin_role_path ,:class=>'usuallink bold_text'%>
</p>-->

app/views/super_admin/roles/new.html.erb
<% title "Groups: New Group" %>
<% content_for :sub_heading do %>
  <%= sub_heading('Groups','Create Group') %>
<% end %>
<div class="help_text">
 Area for managing groups used to assign certain permissions to LSSSP service sections for different groups members. <br/>
 Along with creating, managing and removing groups for your LSSSP service users,.
</div>
<%= render 'form' %>
<div class="link_buttons">
 <%=link_to_all(super_admin_roles_path)%>
</div>

app/views/super_admin/roles/permissions.html.erb
<% title "Lsssp : Manage Groups" %>
<% content_for :sub_heading do %>
  <%= sub_heading('Group',"#{@role.name} | Assign Permissions") %>
<% end %>
<div style="width:530px;" align="center">
 <%=form_for @role,:url=>{:action=>'assign_permissions'}  do |f| %>
   <%= f.error_messages %>
   
   <table cellspacing="1" cellpadding="5" border="0" class="tablesorter" align="center">
	 <tbody>
       <tr>
		 <th width="35%">Module</th>
         <th width="20%">Allow</th>
       </tr>
    <% ABILITIES.each do |key,values|%>  
	   <tr>
		 <td align="left"><b><%= key %></b></td>
		 <td align="center">
           <%=check_box_tag "role[authorizations_attributes][][name]", key,@role.authorizations.map(&:name).include?(key)%>
         </td>
	   </tr>
      <% ABILITIES[key].each do |val| %>
         <% authorization = Authorization.find_by_role_id_and_name(@role.id,key) %>
	    <tr>
		 <td align="right"><%=val%></td>
		 <td align="center">
           <%=check_box_tag "role[authorizations_attributes][][permissions_attributes][][name]", val,
                      (authorization.permissions.map(&:name).include?(val) if authorization ) %>
         </td>
	   </tr>
        
       <% end %>
      
    <% end %>
	 </tbody>
   </table>
  <div align="center"><%= f.submit 'Assign Permissions',:disable_with=>'wait...'%></div>
 <% end %>
</div>
<!--
<%=form_for @role,:url=>{:action=>'assign_permissions'}  do |f| %>
<%= f.error_messages %>
<% auth_attr,perm_attr = 0,0 %>
<% ABILITIES.each do |key,values|%>   
        <%=check_box_tag "role[authorizations_attributes][#{auth_attr}][name]", key,@role.authorizations.map(&:name).include?(key)%><%= key %><br/>
           <% ABILITIES[key].each do |val| %>
             <% authorization = Authorization.find_by_role_id_and_name(@role.id,key) %>
             <%=check_box_tag "role[authorizations_attributes][#{auth_attr}][permissions_attributes][#{perm_attr}][name]", val,
                      (authorization.permissions.map(&:name).include?(val) if authorization ) %><%=val%>
             <% perm_attr += 1 %>
           <% end %>
 <% auth_attr +=1 %><br/>
<% end %>
<%= f.submit 'Save',:disable_with=>'wait...'%>
<% end %>

-->

<!--
<%=form_for @role,:url=>{:action=>'assign_permissions'} ,:validate=>true do |f| %>
<%= f.error_messages %>
<%= f.fields_for :authorizations do |a| %>
Model : <%=a.text_field :name%>
Permissions :
<%=a.fields_for :permissions do |p| %>

<%=p.check_box :name ,{},p.object.name %><%=p.object.name%>
<% end %>
<br/>
<% end %>
<%=f.submit 'Save',:disable_with=>'wait...'%>
<% end %>

-->

app/views/super_admin/roles/show.html.erb
<% title "LSSSP | Group : #{@role.name}" %>
<% content_for :sub_heading do %>
  <%= sub_heading('Groups',"#{@role.name}") %>
<% end %>
<div class="formbox">
  <div class="desc"><b>Name</b> :  <%= @role.name %></div>
  <div class="divider"></div>
  <div class="desc"><b>Description</b> : <%= @role.description %> </div>
  <div class="divider"></div>
  <div class="desc"><b>Status</b> :  <%= @role.active? ? 'Active' : 'Pending' %>
  </div>
</div>
<!--<div class="link_buttons">
   <%=link_to_edit(edit_super_admin_role_path(@role)) %>
   <%=link_to_delete([:super_admin, @role]) %>
   <%=link_to_all(super_admin_roles_path)%>
   <%=link_to_back %>
</div>-->