config/routes.rb
LssspP2::Application.routes.draw do
  resources :credits

  resources :examinations do
    get 'active', :on=>:member
    get 'export', :on=>:collection

  end

  resources :coupons
  resources :verifications

  get "user_info/index"
  devise_for :users, :path_names => {:sign_up => "register"}
=begin
devise_for :users, :as => "", :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }
match "login" => "devise/sessions#new", :as => :new_user_session
match "logout" => "devise/sessions#destroy", :as => :destroy_user_session
match "register" => "devise/registrations#new", :as => :new_user_registration
=end
  resources :followings

  #Superadmin Namespace
  #--------------------------------------------------------------------------
  namespace :super_admin do
    resources :users do
      get 'approve', :on=>:member
      get 'profile', :on=>:member
      get 'upload', :on=>:collection
      get 'export', :on=>:collection
      get 'reset', :on=>:member
      post 'csv_import',:on=>:collection
    end
    #---------------------------------------------------------------------------
    # ROles
    #---------------------------------------------------------------------------
    resources :roles do
      member do
        get 'permissions'
        put 'assign_permissions'
        get 'active'
      end
      get 'export', :on=>:collection
    end
  end
  #--------------------------------------------------------------------------
  #Student namespace
  #--------------------------------------------------------------------------
  namespace :student do
    resources :service_providers do
      get 'my_service_providers', :on=>:collection
      post 'coupon_check',:on=>:collection
    end
    resources :certifications, :only => [:index] do
      get 'assignments', :on=>:member
      get 'download', :on=>:member
      get 'assign',:on=>:member
      get 'subscribe', :on=>:member
    end
    #resource :exam
  end
  ######## Exam
  match "exam/:id/:status" => "student/exam#index", :as=>:exam
  match "active_question" => "student/exam#active_question", :as=>:active_question
  match "update_answer" => "student/exam#update_answer"
  match "finish_exam/:id" => "student/exam#finish_exam", :as=>:finish_exam

  match "save_exam/:id" => "student/exam#save_exam", :as=>:save_exam

  match "review_question" => "student/exam#review_question"

  ###### Subscribe/Unsubscribe exam for user from super_admin
  match "/:name/:id/subscribe_to/:provider_id"=>"student/certifications#subscribe",:as=>:subscribe_certification
  match "/:id/un_subscribe"=>"student/certifications#un_subscribe",:as=>:un_subscribe_certification

  #--------------------------------------------------------------------------
  #Service Provider Namespace
  #--------------------------------------------------------------------------
  namespace :service_provider do
    resources :certifications do
      get 'my_certifications', :on=>:collection
      get 'export', :on=>:collection
    end
    resources :assessors, :students do
      get 'approve', :on=>:member
      get 'export', :on=>:collection
      get 'students', :on=>:member
    end
  end
  #--------------------------------------------------------------------------
  namespace :assessor do
    resources :assignments
    resources :students, :only => [:index] do
      get 'manage_assignments', :on=>:collection
      post 'manage_assignments', :on=>:collection
      get 'pending_assignments', :on=>:collection
      post 'pending_assignments', :on=>:collection
      post 'assign_assignments', :on=>:collection
      get 'assignments', :on=>:member
      get 'download', :on=>:member
      #  post 'update_assignment_result' ,:on=>:member
    end
  end
  #namespace(:assessor){ resources :assignments }
  #----------------------------------------------------------------------------
  namespace :catalog do
    resources :topics, :subtopics do
      get 'active', :on=>:member
      get 'export', :on=>:collection

    end
    resources :certifications do
      get 'active', :on=>:member
      get 'export', :on=>:collection
      get 'load_subtopics', :on=>:collection
    end
    resources :questions do
      get 'active',:on=>:member
      get 'export',:on=>:collection
     end
  end

  resources :payment_gateways do
    get 'active', :on=>:member
  end

  #match "certifications/purchased" => "certification/exams#purchased",:as=>:certifications_purchased
  match "certifications/purchased" => "certifications#index", :as=>:certifications_purchased
  match "certification/purchased" => "certifications#purchased_certification" #,:as=>:purchased_certification
  match "certifications/exams" =>"certifications#exams"
  match "manage_certifications" =>"certifications#manage_certifications"
  match "user_info/:id" => "user_info#index", :as=>:user_info
  match "certifications/purchased/:id/edit_score" => "certifications#edit_score", :as=>:edit_score
  match "certifications/purchased/:id/update_score" => "certifications#update_score", :as=>:update_score

  root :to => "home#index"

# Note: This route will make all actions in every controller accessible via GET requests.
  match ':controller(/:action(/:id(.:format)))'
end

app/controllers/assessor/students_controller.rb
class Assessor::StudentsController < ApplicationController
  before_filter :authenticate_user!#,:must_be_assessor
  before_filter :load_certifications,:only=>[:pending_assignments,:manage_assignments]
  def index
    @users = current_user.students.joins(:owned_certifications)#(params[:approved])  Toget only assessor students who has at least one owned_certification
  end

  def pending_assignments
    @owned_certifications = OwnedCertification.pending_assignments(current_user,params[:certification_id]).paginate(:page =>params[:page],:per_page=>10 )
    @assignments =  Assignment.where(:certification_id=>params[:certification_id]) unless params[:certification_id].blank?
  end

  def manage_assignments
    @owned_certifications = OwnedCertification.manage_assignments(current_user,params[:certification_id]).paginate(:page =>params[:page],:per_page=>10 )
  end

  def assign_assignments
    @student_assignments = []
    StudentAssignment.transaction do
      for a in  params[:assignment_ids]
        for oid in params[:owned_certification_ids]
          @student_assignments << StudentAssignment.new(:owned_certification_id=>oid,:assignment_id=>a,:assigner_id=>current_user.id)
        end
      end
      if @student_assignments.all?(&:valid?)
        @student_assignments.each(&:save!)
        flash[:notice] = "Assigned Successfully"
        redirect_to :action=>'pending_assignments'
      else
        flash[:error] = "Error while assigning."
        render 'pending_assignments'
      end
    end
  end

  def assignments
    @owned_certification = OwnedCertification.includes([:certification,{:student_assignments=>{:assignment=>:attachments}}]).find(params[:id])
  end

  def download
    @attachment = CompletedAttachment.find(params[:id])
    send_file @attachment.hanger.path, :type => @attachment.hanger_content_type, :disposition => 'inline'
  end

  def update_assignment_result
    @owned_certification = OwnedCertification.find(params[:id])
    @owned_certification.update_attribute('student_assignments_result',params[:owned_certification][:student_assignments_result])
    flash[:notice] = "Assignment Result Updated.."
    redirect_to :action=>:manage_assignments
  end

  private
  def load_certifications
    @certifications = Certification.active
  end

end

app/controllers/service_provider/assessors_controller.rb
class ServiceProvider::AssessorsController < ApplicationController
  before_filter :authenticate_user!,:must_be_service_provider
  def index
    @users = current_user.assessors(params[:approved]).paginate(:page =>params[:page], :per_page=>20).order("created_at DESC")
    @user = User.new(:role_id=>params[:id])
  end

# only the students belongs to this service provider are assign to an assessor
  def show
    @assessor = User.find(params[:id])
    #@students = current_user.students - @assessor.students # assign this service provider students to an assessor ,they are not assigned to an Assessor already.
    students = current_user.students.joins(:owned_certifications)#(params[:approved])  Toget only this service provider students who has at least one owned_certification
    @students = students - @assessor.students # assign this service provider students to an assessor ,they are not assigned to an Assessor already

  end

  def update
    assessor = User.find(params[:id])
    for student_id in params[:student_ids]
      assessor.inverse_followings.create(:user_id=>student_id)
    end
    redirect_to service_provider_assessor_path(@assessor),:notice=>"Students Assigned Successfully.."
  end

  def destroy
    assessor = User.find(params[:id])
    if params[:commit] == "Remove"
      Following.delete(:user_id=>params[:student_ids],:follower_id=>assessor.id)
      flash[:notice]="Students Removed Successfully.."
    else
      for student_id in params[:student_ids]
        Following.find_by_user_id_and_follower_id(student_id,assessor.id).update_attribute('follower_id',params[:user][:assessor_id])
      end
      flash[:notice]="Students Transferred Successfully.."
    end
    redirect_to students_service_provider_assessor_path(@assessor)
  end

  def approve
    @user = User.find(params[:id])
    @user.update_attribute('approved',@user.approved? ? false : true)
    respond_to do |format|
      format.js
    end
  end

  def students
    @assessor = User.find(params[:id])
    @students = @assessor.students
    @assessors = current_user.assessors #Available Assessors
  end

  def export
    require 'fastercsv'
    users =  current_user.assessors(params[:approved])
    outfile = "Users-" + Time.now.strftime("%d-%m-%Y-%H-%M-%S") + ".csv"
    csv_data = FasterCSV.generate do |csv|
      csv << ["Name","Email","Registration Date","Approved?"]
      users.each do |user|
        csv << [user.name,user.email,user.created_at,user.approved? ? 'yes' : 'no']
      end
    end
    send_data csv_data,
              :type => 'text/csv; charset=iso-8859-1; header=present',
              :disposition => "attachment; filename=#{outfile}"
  end
    def new
       respond_to do |format|
      format.json { render :json => @user }
      format.xml { render :xml => @user }
      format.html
    end
  end
end

app/controllers/service_provider/certifications_controller.rb
class ServiceProvider::CertificationsController < ApplicationController
  before_filter :authenticate_user!,:must_be_service_provider
  layout "application", :except => [:show]

  def index
    @certifications = Certification.active
  end

  def my_certifications
     @certifications = current_user.provided_certifications
  end

  def create
    current_user.certificate_providers << CertificateProvider.new(:certification_id => params[:id])
    current_user.save ? flash[:notice] = "Certification Registered Successfully.." : flash[:error] = "Unable to Register Certification."
    redirect_to service_provider_certifications_url
  end

  def destroy
    certificate_provider = current_user.certificate_providers.find(:first,:conditions=>{:certification_id=>params[:id]})
    certificate_provider.destroy
    flash[:notice] = "Certification Un-Registered Successfully."
    redirect_to service_provider_certifications_url
  end

  def show
    @certification = Certification.active.find(params[:id])
  end

end

app/controllers/service_provider/students_controller.rb
class ServiceProvider::StudentsController < ApplicationController
  before_filter :authenticate_user! ,:must_be_service_provider
  def index
    @users = current_user.students(params[:approved]).paginate(:page =>params[:page], :per_page=>20).order("created_at DESC")
    @user = User.new(:role_id=>params[:id])
  end
  def approve
    @user = User.find(params[:id])
    @user.toggle! :approved #update_attribute('approved',@user.approved? ? false : true)
    respond_to do |format|
      format.js
    end
  end
  def export
    require 'fastercsv'
    users =  current_user.students(params[:approved])
    outfile = "Users-" + Time.now.strftime("%d-%m-%Y-%H-%M-%S") + ".csv"
    csv_data = FasterCSV.generate do |csv|
      csv << ["First Name", "Last Name", "Enrollment #", "Email", "Primary Contact", "Status", "Created At"]
      users.each do |u|
        csv << [u.name, u.last_name, u.enrollment_no, u.email, u.primary_number, u.approved? ? 'Yes' : 'No', u.created_at.strftime('%m.%b.%y')]
      end
    end
    send_data csv_data,
              :type => 'text/csv; charset=iso-8859-1; header=present',
              :disposition => "attachment; filename=#{outfile}"
  end
  def new
       respond_to do |format|
      format.json { render :json => @user }
      format.xml { render :xml => @user }
      format.html
    end
  end
end

app/controllers/student/certifications_controller.rb
class Student::CertificationsController < ApplicationController
  uses_tiny_mce :only=>[:assignments], :options => {
      :theme => 'advanced',
      :theme_advanced_resizing => true,
      :theme_advanced_resize_horizontal => false,
      :plugins => %w{ table fullscreen }
  }
  layout "application", :except => [:assign]

  def index
    @certifications_owned = current_user.owned_certifications#.search(params[:search])
  end

  def assignments
    @owned_certification = OwnedCertification.includes([:certification,{:student_assignments=>{:assignment=>:attachments}}]).find(params[:id])
  end

  def download
    @attachment = Attachment.find(params[:id])
    send_file @attachment.attachment.path, :type => @attachment.attachment_content_type, :disposition => 'inline'
  end

  def update_assignment
    student_assignment = StudentAssignment.find(params[:id])
    student_assignment.update_attributes(params[:student_assignment])
    owned_certification = student_assignment.owned_certification
    if params[:student_assignment][:status].eql?('completed')
      # update owned_certification.student_assignments_status to true if all of the student_assignments are completed
      owned_certification.update_attribute('student_assignments_status',true) unless owned_certification.student_assignments.map(&:status).include?('pending')
    end
    redirect_to :action=>'assignments',:id=>owned_certification
  end

  def assign
    @user = User.find(params[:id])
    @owned_certifications =  @user.owned_certifications
    @providing_certifications = CertificateProvider.un_subscribed_certifications(@owned_certifications.map(&:certification_id))
  end

  def subscribe
    certification = Certification.find_by_name(params[:name])
    user = User.find(params[:id])
    owned_certification = OwnedCertification.new(:owned_id=>user.id,:provider_id=>params[:provider_id],:certification_id =>certification.id,:amount=>certification.price)
    # user.owned_certifications <<  owned_certification
    if owned_certification.save
      flash[:notice] = "Subscribed successfully.. "
      owned_certification.create_student_exam(:certification_id=>certification.id,:no_of_questions=>certification.no_of_questions)  #create student_exam for this user
    else
      flash[:error] = "Unable to Subscribe."
    end

    redirect_to super_admin_users_path
  end

  def un_subscribe
    owned_certification = OwnedCertification.find(params[:id])
    # user.owned_certifications <<  owned_certification
    if owned_certification.destroy
      flash[:notice] = "Un Subscribed successfully.. "
    else
      flash[:error] = "Unable to Un Subscribe."
    end
    redirect_to super_admin_users_path
  end

end

app/helpers/assessor/students_helper.rb
module Assessor::StudentsHelper
end

app/helpers/service_provider/assessors_helper.rb
module ServiceProvider::AssessorsHelper
end

app/helpers/service_provider/certifications_helper.rb
module ServiceProvider::CertificationsHelper
end

app/helpers/service_provider/students_helper.rb
module ServiceProvider::StudentsHelper
end

app/helpers/student/certifications_helper.rb
module Student::CertificationsHelper
end

app/helpers/student/exam_helper.rb
module Student::ExamHelper


end

app/helpers/student/service_providers_helper.rb
module Student::ServiceProvidersHelper


end

app/views/service_provider/students/_new.html.erb
<% @enroll = rand(10_000_000_000-1_000_000_000)+1_000_000_000 %>
<%= simple_form_for([:super_admin,@user], :validate => true) do |f| %>

  <%= f.error_messages %>
  <%#= render :partial => 'user_fields', :locals => { :f => f } %>
  <%= f.input :name,:label=>'First Name' %>
  <%= f.input :last_name%>
  <%= f.input :email,:placeholder => 'user@domain.com' %>
  <%= f.input :primary_number,:label=>"Primary Contact Number",:placeholder=>'(Mobile / Telephone. ex: 04412345678)' %>
  <%= f.input :secondary_number,:label=>"Secondary Contact number",:placeholder=>'(Mobile / Telephone. ex: 04412345678)' %>
  <%= f.input :password,:as => :hidden, :input_html => { :value => @enroll }%>
  <%= f.input :password_confirmation,:as => :hidden, :input_html => { :value => @enroll } %>
  <!--<%= f.association :role,:input_html => { :id => 'user_group' },:prompt=>"Select Role" %>-->
   <%= f.input :role_id,:input_html => { :value => 4 },:as=>:hidden %>
   <%= f.input :approved,:input_html => { :value => 1 },:as=>:hidden %>
   <%= f.input :provider_id,:as=>:hidden,:input_html=>{:value=>current_user.id} %>
  <p><%= f.submit "Create",:disable_with=>'Please wait...' %></p>
<% end %>

app/views/service_provider/students/_student.html.erb
<%= content_tag_for(:tr, student, :class=>cycle('even', 'odd')) do -%>
    <!--<td><%= student.following_assessors.size %></td>-->
    <td><%= check_box_tag "student_ids[]", student.id,false,{:id=>"data_#{student.id}"} %></td>

    <td align="left"><%= student.enrollment_no%></td>
    <td align="left">
      <%= link_to highlight(student.name + " " + student.last_name,params[:search]), user_info_path(:id=>student.id), :rel=>user_info_path(:id=>student.id), :class=>'ajax-cluetip' %>
    </td>
    <td align="left"><%= highlight(student.email, params[:search]) %></td>
    <td><%= student.created_at.strftime('%d-%b-.%Y') %></td>
<!--    <td>
      <div id="approve_<%= student.id %>">
        <%= student.approved? ? image_tag('tick.gif') : image_tag('cros.gif') %>
      </div>
    </td>-->
    <td>
    </td>
<% end %>

app/views/service_provider/students/_upload.html.erb
<% form_tag csv_import_super_admin_users_path, :multipart => true do  -%>
<table>
<tr>
    <td>
        <label for="vle_user">
            Select a CSV File :
        </label>
    </td>
    <td>
        <%= file_field_tag :file -%>
        <%= hidden_field_tag 'provider_id',current_user.id %>
        <%= hidden_field_tag 'role_id','4' %>
    </td>
      <td colspan='2'>
        <%= submit_tag 'Submit' -%>
    </td>
</tr>
</table>
<% end -%>

app/views/service_provider/students/approve.js.erb
$("#approve_<%=@user.id%>").html("<%=escape_javascript(link_to @user.approved? ? image_tag('tick.gif') : image_tag('cros.gif'),approve_service_provider_student_path,:remote=>true)%>")

app/views/service_provider/students/index.html.erb
<% title "LSSSP : Service Provider" %>
<% content_for :sub_heading do %>
    <%= sub_heading('Service Provider ', 'Students') %>
<% end %>
<% content_for :left_panel do  %>
    <td valign="top" width="279"> <%= render 'common/search' %>
    </td>
<% end %>
<div class="help_text">
 Area for managing Students. <br/>
</div>
<div id="container">
  <%= link_to "Add New Student", '#' ,:class=>'usuallink bold_text',:id=>'add_new'%> |
  <%= link_to "Import Students", '#' ,:class=>'usuallink bold_text',:id=>'imp_new'%> |
  <%=link_to "Export Students",export_service_provider_students_path(:approved=>params[:approved]),:class=>'usuallink bold_text' %>
  <div class="inline">
  <div align="right" style="float: right;" class="inline">
    Available Credits:
    <% user_credits = User.find(:first, :conditions=>{:id=>current_user.id}).credits %>

    <% if user_credits <= 0 %>
        <font color="#ff0000;"><b><%= user_credits %></b></font>
    <% else %>
        <font color="#005800;"><b><%= user_credits %></b></font>
    <% end %>

  </div>
  </div>
</div>
<br/>

<div id="new_form">
  <%=render 'new' %>
</div>
<div id="import_form">
  <%=render 'upload' %>
</div>
<% if @users.blank? %>
    <div class="error_msg">
      Sorry No Students Found..!
    </div>
<% else %>
    <table class="tablesorter">
      <thead>
      <tr>
        <th></th>
        <th>Enrollment#</th>
        <th>Name</th>
        <th>Email</th>
        <th>Registration Date</th>
        <!--<th>Status</th>-->
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <%= render :partial=>'student', :collection=>@users %>
      </tbody>
    </table>

        <div class="lsssp_pagination">
      <%= page_entries_info @users %> <%= will_paginate @users, :container => false %>
    </div>
<% end %>