config/routes.rb
LssspP2::Application.routes.draw do
  resources :credits

  resources :examinations do
    get 'active', :on=>:member
    get 'export', :on=>:collection

  end

  resources :coupons
  resources :verifications

  get "user_info/index"
  devise_for :users, :path_names => {:sign_up => "register"}
=begin
devise_for :users, :as => "", :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }
match "login" => "devise/sessions#new", :as => :new_user_session
match "logout" => "devise/sessions#destroy", :as => :destroy_user_session
match "register" => "devise/registrations#new", :as => :new_user_registration
=end
  resources :followings

  #Superadmin Namespace
  #--------------------------------------------------------------------------
  namespace :super_admin do
    resources :users do
      get 'approve', :on=>:member
      get 'profile', :on=>:member
      get 'upload', :on=>:collection
      get 'export', :on=>:collection
      get 'reset', :on=>:member
      post 'csv_import',:on=>:collection
    end
    #---------------------------------------------------------------------------
    # ROles
    #---------------------------------------------------------------------------
    resources :roles do
      member do
        get 'permissions'
        put 'assign_permissions'
        get 'active'
      end
      get 'export', :on=>:collection
    end
  end
  #--------------------------------------------------------------------------
  #Student namespace
  #--------------------------------------------------------------------------
  namespace :student do
    resources :service_providers do
      get 'my_service_providers', :on=>:collection
      post 'coupon_check',:on=>:collection
    end
    resources :certifications, :only => [:index] do
      get 'assignments', :on=>:member
      get 'download', :on=>:member
      get 'assign',:on=>:member
      get 'subscribe', :on=>:member
    end
    #resource :exam
  end
  ######## Exam
  match "exam/:id/:status" => "student/exam#index", :as=>:exam
  match "active_question" => "student/exam#active_question", :as=>:active_question
  match "update_answer" => "student/exam#update_answer"
  match "finish_exam/:id" => "student/exam#finish_exam", :as=>:finish_exam

  match "save_exam/:id" => "student/exam#save_exam", :as=>:save_exam

  match "review_question" => "student/exam#review_question"

  ###### Subscribe/Unsubscribe exam for user from super_admin
  match "/:name/:id/subscribe_to/:provider_id"=>"student/certifications#subscribe",:as=>:subscribe_certification
  match "/:id/un_subscribe"=>"student/certifications#un_subscribe",:as=>:un_subscribe_certification

  #--------------------------------------------------------------------------
  #Service Provider Namespace
  #--------------------------------------------------------------------------
  namespace :service_provider do
    resources :certifications do
      get 'my_certifications', :on=>:collection
      get 'export', :on=>:collection
    end
    resources :assessors, :students do
      get 'approve', :on=>:member
      get 'export', :on=>:collection
      get 'students', :on=>:member
    end
  end
  #--------------------------------------------------------------------------
  namespace :assessor do
    resources :assignments
    resources :students, :only => [:index] do
      get 'manage_assignments', :on=>:collection
      post 'manage_assignments', :on=>:collection
      get 'pending_assignments', :on=>:collection
      post 'pending_assignments', :on=>:collection
      post 'assign_assignments', :on=>:collection
      get 'assignments', :on=>:member
      get 'download', :on=>:member
      #  post 'update_assignment_result' ,:on=>:member
    end
  end
  #namespace(:assessor){ resources :assignments }
  #----------------------------------------------------------------------------
  namespace :catalog do
    resources :topics, :subtopics do
      get 'active', :on=>:member
      get 'export', :on=>:collection

    end
    resources :certifications do
      get 'active', :on=>:member
      get 'export', :on=>:collection
      get 'load_subtopics', :on=>:collection
    end
    resources :questions do
      get 'active',:on=>:member
      get 'export',:on=>:collection
     end
  end

  resources :payment_gateways do
    get 'active', :on=>:member
  end

  #match "certifications/purchased" => "certification/exams#purchased",:as=>:certifications_purchased
  match "certifications/purchased" => "certifications#index", :as=>:certifications_purchased
  match "certification/purchased" => "certifications#purchased_certification" #,:as=>:purchased_certification
  match "certifications/exams" =>"certifications#exams"
  match "manage_certifications" =>"certifications#manage_certifications"
  match "user_info/:id" => "user_info#index", :as=>:user_info
  match "certifications/purchased/:id/edit_score" => "certifications#edit_score", :as=>:edit_score
  match "certifications/purchased/:id/update_score" => "certifications#update_score", :as=>:update_score

  root :to => "home#index"

# Note: This route will make all actions in every controller accessible via GET requests.
  match ':controller(/:action(/:id(.:format)))'
end

app/models/student_exam.rb
class StudentExam < ActiveRecord::Base
  belongs_to :owned_certification
  belongs_to :certification
  has_many :active_questions,:order=>'id',:dependent => :destroy


  class << self
    def completed(id)
      id.blank? ? includes([:certification]).where(:complete_status=>true).order('updated_at DESC') :
          includes([:certification]).where(:certification_id=>id,:complete_status=>true).order('updated_at DESC')
    end

    def pending(id)
      id.blank? ? includes([:user,:certification]).where(:complete_status=>false ,:status=>true).order('updated_at DESC') :
          includes([:certification]).where(:certification_id=>id,:complete_status=>false ,:status=>true).order('updated_at DESC')
    end

    def not_yet_attempted(id)
      id.blank? ? includes([:certification]).where(:status=>false).order('updated_at DESC') :
          includes([:certification]).where(:certification_id=>id,:status=>false).order('updated_at DESC')
    end


    def by_status_and_certification(status,id)
      case status
        when 'completed'
          completed(id)
        when 'pending'
          pending(id)
        when 'not_yet_attempted'
          not_yet_attempted(id)
        else
          id.blank? ? includes([:certification]).order('updated_at DESC') :
          includes([:certification]).where(:certification_id=>id).order('updated_at DESC')
      end
    end
  end

end

app/controllers/assessor/students_controller.rb
class Assessor::StudentsController < ApplicationController
  before_filter :authenticate_user!#,:must_be_assessor
  before_filter :load_certifications,:only=>[:pending_assignments,:manage_assignments]
  def index
    @users = current_user.students.joins(:owned_certifications)#(params[:approved])  Toget only assessor students who has at least one owned_certification
  end

  def pending_assignments
    @owned_certifications = OwnedCertification.pending_assignments(current_user,params[:certification_id]).paginate(:page =>params[:page],:per_page=>10 )
    @assignments =  Assignment.where(:certification_id=>params[:certification_id]) unless params[:certification_id].blank?
  end

  def manage_assignments
    @owned_certifications = OwnedCertification.manage_assignments(current_user,params[:certification_id]).paginate(:page =>params[:page],:per_page=>10 )
  end

  def assign_assignments
    @student_assignments = []
    StudentAssignment.transaction do
      for a in  params[:assignment_ids]
        for oid in params[:owned_certification_ids]
          @student_assignments << StudentAssignment.new(:owned_certification_id=>oid,:assignment_id=>a,:assigner_id=>current_user.id)
        end
      end
      if @student_assignments.all?(&:valid?)
        @student_assignments.each(&:save!)
        flash[:notice] = "Assigned Successfully"
        redirect_to :action=>'pending_assignments'
      else
        flash[:error] = "Error while assigning."
        render 'pending_assignments'
      end
    end
  end

  def assignments
    @owned_certification = OwnedCertification.includes([:certification,{:student_assignments=>{:assignment=>:attachments}}]).find(params[:id])
  end

  def download
    @attachment = CompletedAttachment.find(params[:id])
    send_file @attachment.hanger.path, :type => @attachment.hanger_content_type, :disposition => 'inline'
  end

  def update_assignment_result
    @owned_certification = OwnedCertification.find(params[:id])
    @owned_certification.update_attribute('student_assignments_result',params[:owned_certification][:student_assignments_result])
    flash[:notice] = "Assignment Result Updated.."
    redirect_to :action=>:manage_assignments
  end

  private
  def load_certifications
    @certifications = Certification.active
  end

end

app/controllers/certification/exams_controller.rb
class Certification::ExamsController < ApplicationController
   before_filter :authenticate_user!
  def index
    @student_exams = StudentExam.finished.paginate(:page =>params[:page],:per_page=>10 )
  end
  def purchased
    if params[:certification_id]
       @student_certifications = OwnedCertification.by_certification(params[:certification_id]).paginate(:page =>params[:page],:per_page=>10 )
    else
      @student_certifications = OwnedCertification.includes([:user,:provider,:certification]).order('created_at DESC').paginate(:page =>params[:page],:per_page=>10 )
    end
  end
end

app/controllers/service_provider/students_controller.rb
class ServiceProvider::StudentsController < ApplicationController
  before_filter :authenticate_user! ,:must_be_service_provider
  def index
    @users = current_user.students(params[:approved]).paginate(:page =>params[:page], :per_page=>20).order("created_at DESC")
    @user = User.new(:role_id=>params[:id])
  end
  def approve
    @user = User.find(params[:id])
    @user.toggle! :approved #update_attribute('approved',@user.approved? ? false : true)
    respond_to do |format|
      format.js
    end
  end
  def export
    require 'fastercsv'
    users =  current_user.students(params[:approved])
    outfile = "Users-" + Time.now.strftime("%d-%m-%Y-%H-%M-%S") + ".csv"
    csv_data = FasterCSV.generate do |csv|
      csv << ["First Name", "Last Name", "Enrollment #", "Email", "Primary Contact", "Status", "Created At"]
      users.each do |u|
        csv << [u.name, u.last_name, u.enrollment_no, u.email, u.primary_number, u.approved? ? 'Yes' : 'No', u.created_at.strftime('%m.%b.%y')]
      end
    end
    send_data csv_data,
              :type => 'text/csv; charset=iso-8859-1; header=present',
              :disposition => "attachment; filename=#{outfile}"
  end
  def new
       respond_to do |format|
      format.json { render :json => @user }
      format.xml { render :xml => @user }
      format.html
    end
  end
end

app/controllers/student/certifications_controller.rb
class Student::CertificationsController < ApplicationController
  uses_tiny_mce :only=>[:assignments], :options => {
      :theme => 'advanced',
      :theme_advanced_resizing => true,
      :theme_advanced_resize_horizontal => false,
      :plugins => %w{ table fullscreen }
  }
  layout "application", :except => [:assign]

  def index
    @certifications_owned = current_user.owned_certifications#.search(params[:search])
  end

  def assignments
    @owned_certification = OwnedCertification.includes([:certification,{:student_assignments=>{:assignment=>:attachments}}]).find(params[:id])
  end

  def download
    @attachment = Attachment.find(params[:id])
    send_file @attachment.attachment.path, :type => @attachment.attachment_content_type, :disposition => 'inline'
  end

  def update_assignment
    student_assignment = StudentAssignment.find(params[:id])
    student_assignment.update_attributes(params[:student_assignment])
    owned_certification = student_assignment.owned_certification
    if params[:student_assignment][:status].eql?('completed')
      # update owned_certification.student_assignments_status to true if all of the student_assignments are completed
      owned_certification.update_attribute('student_assignments_status',true) unless owned_certification.student_assignments.map(&:status).include?('pending')
    end
    redirect_to :action=>'assignments',:id=>owned_certification
  end

  def assign
    @user = User.find(params[:id])
    @owned_certifications =  @user.owned_certifications
    @providing_certifications = CertificateProvider.un_subscribed_certifications(@owned_certifications.map(&:certification_id))
  end

  def subscribe
    certification = Certification.find_by_name(params[:name])
    user = User.find(params[:id])
    owned_certification = OwnedCertification.new(:owned_id=>user.id,:provider_id=>params[:provider_id],:certification_id =>certification.id,:amount=>certification.price)
    # user.owned_certifications <<  owned_certification
    if owned_certification.save
      flash[:notice] = "Subscribed successfully.. "
      owned_certification.create_student_exam(:certification_id=>certification.id,:no_of_questions=>certification.no_of_questions)  #create student_exam for this user
    else
      flash[:error] = "Unable to Subscribe."
    end

    redirect_to super_admin_users_path
  end

  def un_subscribe
    owned_certification = OwnedCertification.find(params[:id])
    # user.owned_certifications <<  owned_certification
    if owned_certification.destroy
      flash[:notice] = "Un Subscribed successfully.. "
    else
      flash[:error] = "Unable to Un Subscribe."
    end
    redirect_to super_admin_users_path
  end

end

app/controllers/student/service_providers_controller.rb
class Student::ServiceProvidersController < ApplicationController
  before_filter :authenticate_user!,:must_be_student
  layout "application" #, :except => [:subscribe_coupon]

  def index
    #getting service providers who have at least one certification
    @service_providers = User.with_role(2).joins(:provided_certifications).group('users.name')
  end

  def show
    @service_provider = User.find(params[:id])
    @provided_certifications = @service_provider.provided_certifications
    # get an id of service provider and display info of that user
    #student_service_provider_path(id) or [:student, @service_provider]
  end

  def create
    certification = Certification.find(params[:cid])
    owned_certification = OwnedCertification.new(:provider_id=>params[:id],:certification_id =>certification.id,:amount=>certification.price)
    current_user.owned_certifications <<  owned_certification
    if current_user.save
      flash[:notice] = "Payment Success..! Examination Created "
      owned_certification.create_student_exam(:certification_id=>certification.id,:no_of_questions=>certification.no_of_questions)  #create student_exam for this user
      #send mail about the Examination Details
      ExamNotifier.exam_notification(current_user,owned_certification).deliver
    else
      flash[:error] = "Payment Failure."
    end
    # redirect_to student_service_provider_path(params[:id])
    redirect_to  student_certifications_path
  end

  def destroy
    following = Following.find_by_user_id_and_follower_id(current_user.id,params[:id])
    following.delete  ? flash[:notice] = "Removed Service Provider Successfully.." : flash[:error] = "Unable to remove this service provider."
    #TODO remove all student_certifications provided by this service provider to this user
    redirect_to my_service_providers_student_service_providers_path
  end

  def my_service_providers
    @my_service_providers = current_user.following_service_providers
  end

=begin
  def subscribe_coupon
  end
  def coupon_check
    @coupon = Coupon.where(:coupon=>params[:coupon],:provider_id=>params[:id],:status => 0)

    if @coupon.size == 1
    certification = Certification.find(params[:cid])
    owned_certification = OwnedCertification.new(:provider_id=>params[:id],:certification_id =>certification.id,:amount=>certification.price)
    current_user.owned_certifications <<  owned_certification
    if current_user.save
      flash[:notice] = "Coupon Valid..! Examination Created "
      owned_certification.create_student_exam(:certification_id=>certification.id,:no_of_questions=>certification.no_of_questions)  #create student_exam for this user
      @coupon.each do |c|
        c.update_attributes(:student_id=>current_user.id,:redemption_date=>Date.today,:status=>1)
      end
      #send mail about the Examination Details
      ExamNotifier.exam_notification(current_user,owned_certification).deliver
      redirect_to  student_certifications_path

    end
    # redirect_to student_service_provider_path(params[:id])
    else
      flash[:notice] = "Coupon is invalid or Already used...! Please Check with Service Provider "
      redirect_to(:controller => 'student/service_providers',:action=>'show',:id=>params[:id])
    end

  end
=end

end

app/controllers/super_admin/exams_controller.rb
class SuperAdmin::ExamsController < ApplicationController
  def index
    @student_exams = StudentExam.finished.paginate(:page =>params[:page],:per_page=>10 )
  end
end

app/helpers/assessor/students_helper.rb
module Assessor::StudentsHelper
end

app/helpers/certification/exams_helper.rb
module Certification::ExamsHelper
end

app/helpers/service_provider/students_helper.rb
module ServiceProvider::StudentsHelper
end

app/helpers/student/certifications_helper.rb
module Student::CertificationsHelper
end

app/helpers/student/exam_helper.rb
module Student::ExamHelper


end

app/helpers/student/service_providers_helper.rb
module Student::ServiceProvidersHelper


end

app/helpers/super_admin/exams_helper.rb
module SuperAdmin::ExamsHelper
end

app/views/student/exam/_question.html.erb
<div class="pagination">
  <%= link_to content_tag(:span, '← Previous '), active_question_path(:id=>@active_question.id-1, :previous=>true), :remote=>true, :id=>"load_question", :class=>'btn-blue previous_page', :style=>'float:right' %>
  <%= link_to content_tag(:span, ' Next →'), active_question_path(:id=>@active_question.id+1, :next=>true), :remote=>true, :id=>"load_question", :class=>'btn-yellow next_page', :style=>'float:right' %>
</div>


<div id="finish_button">
  <%= link_to content_tag(:span, 'Finish Exam'), finish_exam_path(:id=>@active_question.student_exam_id), :class=>'btn-red', :style=>'float:none', :confirm => "You are about to submit your exam for final evaluation. Are you sure you want to submit your exam?" %>
  <!--<%= link_to content_tag(:span, 'Finish Exam'), finish_exam_path(:id=>@active_question.student_exam_id), :class=>'btn-red', :style=>'float:none', :id=>"yesno" ,:title=>"You are about to submit your exam for final evaluation. Are you sure you want to submit your exam?" %>-->

</div>

<div id="question_content">
  <%= hidden_field_tag 'id', @active_question.id %>
  <h2>Question <%= session[:active_question_ids].index(@active_question.id)+1 %></h2>

  <div class="rbox question_body">
    <p><%= @active_question.question.content %>
      <% if @active_question.question.question? %>
          <%= image_tag @active_question.question.question.url(:thumb) %>
          <a href='<%= @active_question.question.question.url %>' rel="facebox">Click to Enlarge this image</a>
      <% else %>
      <% end %>
    </p>
  </div>
  <div class="rbox" id="answers">
    <table class="answers_go">
      <tbody>
      <% i = 1 %>
      <% for answer in @active_question.question.answers %>
          <tr>
            <td class="checkbox">
              <%= check_box_tag "correct_answer[]", i, @active_question.correct_answer.to_a.include?(i) -%>
            </td>
            <td class="answer"><p><code><%= answer.content %>
              <% if answer.answer? %>
                  <%= image_tag answer.answer.url(:thumb) %>
                  <a href='<%= answer.answer.url %>' rel="facebox">Click to Enlarge this image</a>
              <% else %>
              <% end %>
            </code></p></td>
          </tr>
          <% i += 1 %>
      <% end %>
      </tbody>
    </table>
    <%= submit_tag 'Update Answer', :style=>'display:none;' %>
  </div>
</div>

<%# If useful repeat next ,previous links here %>
<script type="text/javascript">
    jQuery(document).ready(function($) {
        $('a[rel*=facebox]').facebox()
    })
</script>
<script language="javascript">
    $(document).bind('reveal.facebox', function() {
        $('#facebox').draggable();
    })
</script>

	<script type="text/javascript">
	$(function() {


		$("#yesno").easyconfirm({locale: { title: 'Confirm', button: ['No','Yes']}});


	});
	</script>
	<style type="text/css">
	.ui-dialog { font-size: 12px; }

	</style>

app/views/student/exam/_review_question.html.erb
<div id="question_content">
  <h2>Question <%= params[:q_number] ||=1 %></h2>

  <div class="rbox question_body">
    <p><%= @active_question.question.content %>
      <% if @active_question.question.question? %>
          <%= image_tag @active_question.question.question.url(:thumb) %>
          <a href='<%= @active_question.question.question.url %>' rel="facebox">Click to Enlarge this image</a>
      <% else %>
      <% end %>

    </p>
  </div>
  <div class="rbox" id="answers">
    <table class="answers_go">
      <tbody>
      <tr>
        <th colspan="2">Your Answers</th>
        <th>Correct Answers</th>
      </tr>
      <% i = 1 %>
      <% for answer in @active_question.question.answers %>

          <tr>
            <td class="checkbox">
              <%= check_box_tag "correct_answer[]", i, @active_question.correct_answer.to_a.include?(i) -%>
            </td>
            <td class="answer"><p><code><%= answer.content %>
              <% if answer.answer? %>
                  <%= image_tag answer.answer.url(:thumb) %>
                  <a href='<%= answer.answer.url %>' rel="facebox">Click to Enlarge this image</a>
              <% else %>
              <% end %>

            </code></p></td>
            <td class="checkbox"> <%= check_box_tag "correct_answer[]", i, @active_question.question.correct_answer.to_a.include?(i) -%></td>
          </tr>
          <% i += 1 %>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<script type="text/javascript">
    jQuery(document).ready(function($) {
        $('a[rel*=facebox]').facebox()
    })
</script>
<script language="javascript">
    $(document).bind('reveal.facebox', function() {
        $('#facebox').draggable();
    })
</script>

app/views/student/exam/active_question.js.erb
// to remove class eg: class="current completed" the below line removes only 'current' class not 'completed'
$(".current").removeClass("current");
<% type = active_question_status(@active_question) %>
$("#active_question_<%= @active_question.id %>").addClass("current <%=type%>")
$("#active_question_<%= params[:id] %>").attr('title', 'Viewed')
$('#question').html("<%= escape_javascript(render 'question') %>")

app/views/student/exam/finish_exam.html.erb
<div id="exam_content">
  <h3>Review Examination - <%= @student_exam.certification.name %></h3>
  <div id="pagination_container">
    <div>
      <h2>Your Score(Percentage)  : <span id="score"><%= @student_exam.percentage %>%</span></h2>
      <ul id="score_summary">
        <li class="usuallink tipTip" title="Total Number of questions in Examination">Total Questions: <%= @student_exam.no_of_questions %></li>
        <li class="usuallink tipTip" title="Number of questions visited">Questions Visited: <%= @student_exam.visited %></li>
        <li class="usuallink tipTip" title="Number of questions Answered">Questions Answered: <%= @student_exam.answered %></li>
        <li class="usuallink tipTip" title="Number of questions with correct answers">Correct Answered Questions: <%= @student_exam.answered_correctly %></li>
      </ul>
    </div>
    <ol class="questions_summary">
      <% i = 1 %>
      <% @active_questions.each do |active_question| %>
          <li title="current" id="active_question_<%=active_question.id%>">
            <%= link_to review_question_path(:id=>active_question.id,:q_number=>i),:remote => true,:id=>"load_question"  do %>
                <% answer = active_question.correct_answer.eql?(active_question.question.correct_answer) ? 'correct' : 'incorrect'  %>
                Q<span class="answer"><%=i%></span>: <%= image_tag( answer.eql?('correct') ? 'tick.gif' : 'cros.gif') %>
            <% end %>
          </li>
          <% i += 1%>
      <% end %>
    </ol>
  </div>
  <div id="question">
    <%= render 'review_question' %>
  </div>
</div>
<div id="ajax-indicator">
  <span> Loading Question......</span>
</div>

app/views/student/exam/index.html.erb
<div id="exam_content">
  <div align="right">
    <b>Time Left: </b>
    <input id="disp" readonly="true" type="text" border="0" name="disp" size="5" class="inputtext" align="center">
    <br/>

  </div>
  <h3><%= @student_exam.certification.name %></h3>

  <p><%= @student_exam.certification.name %> is of <%= @student_exam.certification.duration %> minutes
    containing <%= @student_exam.certification.no_of_questions %> questions and needs a minimum
    of <%= @student_exam.certification.pass_marks_percentage %>% to successfully pass this exam.</p>

  <div id="pagination_container">
    <ul id="questions_pagination" class="pagination">
      <% i = 1 %>
      <% @active_questions.each do |active_question| %>
          <% type = active_question_status(active_question) %>
          <li title="<%= type.capitalize %>" class="<%= active_question.id.eql?(@active_question.id) ? "current "+type : type %>" id="active_question_<%= active_question.id %>">
            <%= link_to i, active_question_path(:id=>active_question.id, :q_number=>i), :remote => true, :id=>"load_question" %>
          </li>
          <% i += 1 %>
      <% end %>
    </ul>
  </div>
  <%= form_tag update_answer_path, :remote=>true, :id=>'exam_update_answer' do %>
      <div id="question">
        <%= render 'question' %>
      </div>
  <% end %>
</div>
<div id="ajax-indicator">
  <span> Loading...</span>
</div>

<script type="text/javascript">
    var mins;
    var secs;

    function countDown() {
        mins = 1 * minutes("<%= @student_exam.certification.duration %>"); // change minutes here
        secs = 0 + seconds(":01"); // change seconds here (always add an additional second to your total)
        redo();
    }

    function minutes(obj) {
        for (var i = 0; i < obj.length; i++) {
            if (obj.substring(i, i + 1) == ":")
                break;
        }
        return (obj.substring(0, i));
    }

    function seconds(obj) {
        for (var i = 0; i < obj.length; i++) {
            if (obj.substring(i, i + 1) == ":")
                break;
        }
        return (obj.substring(i + 1, obj.length));
    }

    function dis(mins, secs) {
        var disp;
        if (mins <= 9) {
            disp = " 0";
        }
        else {
            disp = " ";
        }
        disp += mins + ":";
        if (secs <= 9) {
            disp += "0" + secs;
        }
        else {
            disp += secs;
        }
        return (disp);
    }

    function redo() {
        secs--;
        if (secs == -1) {
            secs = 59;
            mins--;
        }
        document.getElementById('disp').value = dis(mins, secs); // setup additional displays here.
        if ((mins == 0) && (secs == 0)) {
            window.alert("Exam Time is up. Press OK to continue view your score."); // change timeout message as required
            window.location = "<%= finish_exam_path(:id=>@active_question.student_exam_id) %>" // redirects to specified page once timer ends and ok button is pressed
        }
        else {
            cd = setTimeout("redo()", 1000);
        }
    }

    function init() {
        countDown();

    }

    window.onload = init;


</script>

<script type="text/javascript">
    $(function() {


        $("#yesno").easyconfirm({locale: { title: 'Confirm', button: ['No','Yes']}});


    });
</script>
<style type="text/css">
    .ui-dialog {
        font-size: 12px;
    }

</style>

app/views/student/exam/review_question.js.erb
$('#question').html("<%= escape_javascript(render 'review_question') %>")

app/views/student/exam/update_answer.js.erb
<% if @active_question.correct_answer.nil? %>
$("#active_question_<%= params[:id] %>").attr('class', 'current viewed')
$("#active_question_<%= params[:id] %>").attr('title', 'Viewed')
<% else %>
$("#active_question_<%= params[:id] %>").attr('class', 'current completed')
$("#active_question_<%= params[:id] %>").attr('title', 'Completed')
<% end %>