config/routes.rb
LssspP2::Application.routes.draw do
  resources :credits

  resources :examinations do
    get 'active', :on=>:member
    get 'export', :on=>:collection

  end

  resources :coupons
  resources :verifications

  get "user_info/index"
  devise_for :users, :path_names => {:sign_up => "register"}
=begin
devise_for :users, :as => "", :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }
match "login" => "devise/sessions#new", :as => :new_user_session
match "logout" => "devise/sessions#destroy", :as => :destroy_user_session
match "register" => "devise/registrations#new", :as => :new_user_registration
=end
  resources :followings

  #Superadmin Namespace
  #--------------------------------------------------------------------------
  namespace :super_admin do
    resources :users do
      get 'approve', :on=>:member
      get 'profile', :on=>:member
      get 'upload', :on=>:collection
      get 'export', :on=>:collection
      get 'reset', :on=>:member
      post 'csv_import',:on=>:collection
    end
    #---------------------------------------------------------------------------
    # ROles
    #---------------------------------------------------------------------------
    resources :roles do
      member do
        get 'permissions'
        put 'assign_permissions'
        get 'active'
      end
      get 'export', :on=>:collection
    end
  end
  #--------------------------------------------------------------------------
  #Student namespace
  #--------------------------------------------------------------------------
  namespace :student do
    resources :service_providers do
      get 'my_service_providers', :on=>:collection
      post 'coupon_check',:on=>:collection
    end
    resources :certifications, :only => [:index] do
      get 'assignments', :on=>:member
      get 'download', :on=>:member
      get 'assign',:on=>:member
      get 'subscribe', :on=>:member
    end
    #resource :exam
  end
  ######## Exam
  match "exam/:id/:status" => "student/exam#index", :as=>:exam
  match "active_question" => "student/exam#active_question", :as=>:active_question
  match "update_answer" => "student/exam#update_answer"
  match "finish_exam/:id" => "student/exam#finish_exam", :as=>:finish_exam

  match "save_exam/:id" => "student/exam#save_exam", :as=>:save_exam

  match "review_question" => "student/exam#review_question"

  ###### Subscribe/Unsubscribe exam for user from super_admin
  match "/:name/:id/subscribe_to/:provider_id"=>"student/certifications#subscribe",:as=>:subscribe_certification
  match "/:id/un_subscribe"=>"student/certifications#un_subscribe",:as=>:un_subscribe_certification

  #--------------------------------------------------------------------------
  #Service Provider Namespace
  #--------------------------------------------------------------------------
  namespace :service_provider do
    resources :certifications do
      get 'my_certifications', :on=>:collection
      get 'export', :on=>:collection
    end
    resources :assessors, :students do
      get 'approve', :on=>:member
      get 'export', :on=>:collection
      get 'students', :on=>:member
    end
  end
  #--------------------------------------------------------------------------
  namespace :assessor do
    resources :assignments
    resources :students, :only => [:index] do
      get 'manage_assignments', :on=>:collection
      post 'manage_assignments', :on=>:collection
      get 'pending_assignments', :on=>:collection
      post 'pending_assignments', :on=>:collection
      post 'assign_assignments', :on=>:collection
      get 'assignments', :on=>:member
      get 'download', :on=>:member
      #  post 'update_assignment_result' ,:on=>:member
    end
  end
  #namespace(:assessor){ resources :assignments }
  #----------------------------------------------------------------------------
  namespace :catalog do
    resources :topics, :subtopics do
      get 'active', :on=>:member
      get 'export', :on=>:collection

    end
    resources :certifications do
      get 'active', :on=>:member
      get 'export', :on=>:collection
      get 'load_subtopics', :on=>:collection
    end
    resources :questions do
      get 'active',:on=>:member
      get 'export',:on=>:collection
     end
  end

  resources :payment_gateways do
    get 'active', :on=>:member
  end

  #match "certifications/purchased" => "certification/exams#purchased",:as=>:certifications_purchased
  match "certifications/purchased" => "certifications#index", :as=>:certifications_purchased
  match "certification/purchased" => "certifications#purchased_certification" #,:as=>:purchased_certification
  match "certifications/exams" =>"certifications#exams"
  match "manage_certifications" =>"certifications#manage_certifications"
  match "user_info/:id" => "user_info#index", :as=>:user_info
  match "certifications/purchased/:id/edit_score" => "certifications#edit_score", :as=>:edit_score
  match "certifications/purchased/:id/update_score" => "certifications#update_score", :as=>:update_score

  root :to => "home#index"

# Note: This route will make all actions in every controller accessible via GET requests.
  match ':controller(/:action(/:id(.:format)))'
end

app/views/common/_assessor_menu.html.erb
<ul class="page_menu">
 <!-- <li><%= tab_heading 'Manage Assignments' %>
    <ul>
      <li><%= link_to 'List Assignments', {:controller=>'/assessor/assignments'} %></li>
    </ul>
  </li>-->
  <li><%= tab_heading 'User Management' %>
    <ul>
      <li><%= link_to 'List My Students', assessor_students_path %></li>
<!--
      <li><%= link_to 'Pending Assignments', {:controller=>'/assessor/students', :action=>'pending_assignments'} %></li>
      <li><%= link_to 'Mange Assignments', {:controller=>'/assessor/students', :action=>'manage_assignments'} %></li>
-->
    </ul>
  </li>
   <li><%= tab_heading 'Manage Assignments' %>
    <ul>
      <li><%= link_to 'Pending Assignments', {:controller=>'/assessor/students', :action=>'pending_assignments'} %></li>
      <li><%= link_to 'Mange Assignments', {:controller=>'/assessor/students', :action=>'manage_assignments'} %></li>
    </ul>
</ul>

app/views/common/_flash_message.html.erb
<div id="flash_messages">
	<% flash.each do |name, msg| %>
	<%= content_tag :div, :id => "flash_#{name}",:class =>"flash_#{name}"  do %>
	<%= msg %>
	<%= content_tag :span, :style => "float: right;" do %>
	<%= link_to_function 'close',:title=>'Close',
	:onclick => "document.getElementById('flash_#{name}').style.display='none'" %>
	<% end %>
	<% end %>
	<% end %>
</div>

app/views/common/_footer.html.erb
<div class="copyright_text">
    <div>
        &copy;2011. The site is optimized to Mozilla Firefox V3+, Google Chrome V5+ and IE8+ Versions.
    </div>
</div>

app/views/common/_header.html.erb
<div id="page_top">
	<%= link_to image_tag("adminlogo.png",:border => 0),root_url%>
	<div id="top_menu">
		<div id="top_m">
			<ul class="top_menu">
				<% if user_signed_in? %>
                  <% if current_user.avatar.file? %>
                  <li><%= image_tag current_user.avatar.url(:small) %></li>
                  <% else %>
                      <li><%= image_tag "avatar.gif",:size => "25x25" %></li>

                  <% end %>
                 <li>Welcome <%= current_user.email %></li>
<!--                  <% if can? :manage,Role %>
                 <li><%=(link_to 'Manage Groups',super_admin_roles_path) %></li>
                  <% end %>-->
				 <li><%=link_to 'Profile',edit_user_registration_path %></li>
                  <li><%= link_to "Sign out", destroy_user_session_path %></li>
                <% else %>
                  <%= link_to "Employee Verification",verifications_url %>
                  <li><%= link_to "Register", new_user_registration_path %></li>
                  <li><%= link_to "Sign in", new_user_session_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/common/_menu.html.erb
<ul class="page_menu">
    <li><%= tab_heading 'Dashboard' %>
    <ul>
      <li><%= link_to 'Certifications Control', certifications_purchased_path %></li>
    </ul>
  </li>
  <li><%= tab_heading 'Users' %>
    <ul>
      <li><%= link_to 'Manage Groups', super_admin_roles_path %></li>
      <li><%= link_to 'Manage Users', super_admin_users_path %></li>
    </ul>
  </li>
  <li><%= tab_heading 'Question Bank' %>
    <ul>
      <li><%= link_to 'Manage Topics', catalog_topics_path %></li>
      <!--<li><%= link_to 'Manage Sub Topics', catalog_subtopics_path %></li>-->
      <li><%= link_to 'Manage Questions', catalog_questions_path %></li>
    </ul>
  </li>
  <li><%= tab_heading 'Certifications' %>
    <ul>
      <li><%= link_to 'Mange Certifications', catalog_certifications_path %></li>
      <li><%= link_to 'Manage Examinations',  examinations_path%></li>
      <li><%= link_to 'Manage Assignment', assessor_assignments_path %></li>


    </ul>
  </li>
   <li><%= tab_heading 'Accounts' %>
    <ul>
      <li><%= link_to 'Manage Credits', credits_path%></li>
      <li><%= link_to 'Manage Payment Gateways', payment_gateways_path %></li>
      <!--<li><%= link_to 'Manage Coupon', coupons_path%></li>-->

    </ul>
</ul>

app/views/common/_search.html.erb
<div class="search" style="">
    <div class="margin">
        <h3>Search</h3>
        <div class="searchbox">
            <%= form_tag(controller_name, :method => 'get') do %>
             <%= hidden_field_tag :id, params[:id] %>
            <%= text_field_tag :search, params[:search], :class => "formTextBox tipTipRight",:size=>20, :title=>"Enter String to Search" %>
            <%= submit_tag 'Go', :disable_with=>'...'%>
            <%#= button_for("Go", :button_type => "submit",:class=>'btn-red') %>
            <% end %>
        </div>
    </div>
</div>

app/views/common/_service_provider_menu.html.erb
<ul class="page_menu">
  <li><%= tab_heading 'Certifications' %>
    <ul>
      <li><%=link_to 'Manage Certifications' ,certifications_purchased_path %></li>
      <!--<li><%=link_to 'Registered Certifications' ,my_certifications_service_provider_certifications_path %></li>-->
    </ul>
  </li>
  <li><%= tab_heading 'Students' %>
    <ul>
      <li><%=link_to 'Manage Students' ,service_provider_students_path %></li>
    </ul>
  </li>
  <li><%= tab_heading 'Assessors' %>
    <ul>
      <li><%=link_to 'Manage Assessors' ,service_provider_assessors_path %></li>
    </ul>
  </li>
  <li><%= tab_heading 'Accounts' %>
    <ul>
      <li><%=link_to 'Manage Credits' ,credits_path %></li>
      <li><%=link_to 'Manage Certifications' ,service_provider_certifications_path %></li>
      <!--<li><%=link_to 'Manage Coupons' ,coupons_path %></li>-->
    </ul>
  </li>
</ul>

app/views/common/_student_menu.html.erb
<ul class="page_menu">
  <li><%= tab_heading 'Manage Service Providers' %>
    <ul>
      <li><%=link_to 'My Service Providers' ,student_service_providers_path %></li>
      <!--<li><%=link_to 'List All Service Providers' ,my_service_providers_student_service_providers_path %></li>-->
    </ul>
  </li>
  <li><%= tab_heading 'Manage Certifications' %>
    <ul>
      <li><%=link_to 'Registered Certifications' ,student_certifications_path %></li>
    </ul>
  </li>

</ul>